### ISSUE TITLE
NameError: global name 'dot_parser' is not defined

### ISSUE THREAD

**Issue by psachin** [kdheepak89/c3.py#3]
Ever came across this error?

It rises when run the app

`python app.py`
- Have you tried this on GNU/Linux?. 
- Python-2 or 3 ?

**Comment by kdheepak** [comment]
I'm assuming this is because of pydot. Can you try `pip uninstall pydot; pip install pydot2`?

**Comment by kdheepak** [comment]
To answer your question, I've only used Python2. If you are using Python3, try `pip install pydotplus`.

**Comment by psachin** [comment]
`pydot2` too is not helpful. I'm using Python2

**Comment by kdheepak** [comment]
I was able to solve this problem in two ways.
1. Install older version of `pyparsing` - [http://stackoverflow.com/a/17902926](http://stackoverflow.com/a/17902926)
2. Install `pydotplus`. This is compatible with Python2 and Python3.

Let me know if you still have issues!

**Comment by psachin** [comment]
PR #4 works perfectly for me.

**Comment by kdheepak** [comment]
`pydotplus` did not work for you?

**Comment by psachin** [comment]
Alone `pydotplus` didn't..when I followed stackoverflow's solution, it did.
